ARG NODE_IMAGE_VERSION="22-alpine"

# Install dependencies only when needed
FROM node:${NODE_IMAGE_VERSION} AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --config.dangerouslyAllowAllBuilds=true

# Rebuild the source code only when needed
FROM node:${NODE_IMAGE_VERSION} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY docker/proxy.ts ./src

ARG BASE_PATH

ENV BASE_PATH=$BASE_PATH
ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL="postgresql://user:pass@localhost:5432/dummy"

RUN npm run build-docker

# Production image. Ship the full build + full node_modules and run `next start`.
# NOTE: we intentionally do NOT use Next's standalone output here. With pnpm, the
# standalone node_modules is a partial, symlinked tree containing only what the web
# server traced — the startup scripts' deps (semver, chalk, @prisma/client, ...) end
# up as dangling symlinks, so `check-db` crashes with ERR_MODULE_NOT_FOUND at boot.
# A single real node_modules makes both the scripts and the server resolve cleanly.
FROM node:${NODE_IMAGE_VERSION} AS runner
WORKDIR /app

ARG NODE_OPTIONS

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS=$NODE_OPTIONS
ENV PATH=/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs \
 && apk add --no-cache curl

# node_modules is read-only at runtime -> keep root-owned (avoids a slow recursive chown)
COPY --from=builder /app/node_modules ./node_modules
# .next (ISR/cache) and public (update-tracker may rewrite script.js) must be writable by nextjs
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/generated ./generated
# geo/GeoLite2-City.mmdb is generated by build-geo at build time (gitignored) and read at
# runtime via path.join(process.cwd(), 'geo') in src/lib/detect.ts -> must ship it explicitly.
COPY --from=builder /app/geo ./geo

USER nextjs

EXPOSE 3000

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# start-docker without the standalone server.js: run the same steps, then `next start`.
CMD ["sh", "-c", "node scripts/check-db.js && node scripts/update-tracker.js && next start -p 3000 -H 0.0.0.0"]
